import { json } from '@sveltejs/kit';
import type { RequestHandler } from '@sveltejs/kit';
import { asc, desc, eq } from 'drizzle-orm';
import { getDb, schema } from '$lib/server/db/client';
import { apiError, handleApiError } from '$lib/server/api';
import { conversationInput } from '$lib/server/validation';

export const GET: RequestHandler = async ({ params }) => { try { const id = params.id; if (!id) return apiError('CONVERSATION_NOT_FOUND', 'Conversation not found.', 404); const db = getDb(); const [conversation] = await db.select().from(schema.conversations).where(eq(schema.conversations.id, id)); if (!conversation) return apiError('CONVERSATION_NOT_FOUND', 'Conversation not found.', 404); const rows = await db.select().from(schema.messages).where(eq(schema.messages.conversationId, id)).orderBy(asc(schema.messages.createdAt)); const calls = await db.select({ id: schema.toolCalls.id, toolCallId: schema.toolCalls.toolCallId, toolName: schema.toolCalls.toolName, input: schema.toolCalls.input, output: schema.toolCalls.output, status: schema.toolCalls.status, startedAt: schema.toolCalls.startedAt, completedAt: schema.toolCalls.completedAt }).from(schema.toolCalls).innerJoin(schema.messages, eq(schema.toolCalls.messageId, schema.messages.id)).where(eq(schema.messages.conversationId, id)).orderBy(desc(schema.toolCalls.startedAt)); return json({ conversation, messages: rows, toolCalls: calls }); } catch (error) { return handleApiError(error); } };
export const PATCH: RequestHandler = async ({ params, request }) => { try { const id = params.id; if (!id) return apiError('CONVERSATION_NOT_FOUND', 'Conversation not found.', 404); const body = await request.json(); const parsed = conversationInput.pick({ title: true, model: true, enabledTools: true }).partial().safeParse(body); if (!parsed.success) return apiError('INVALID_INPUT', 'Invalid conversation payload.'); const [conversation] = await getDb().update(schema.conversations).set({ ...parsed.data, updatedAt: new Date() }).where(eq(schema.conversations.id, id)).returning(); if (!conversation) return apiError('CONVERSATION_NOT_FOUND', 'Conversation not found.', 404); return json({ conversation }); } catch (error) { return handleApiError(error); } };
export const DELETE: RequestHandler = async ({ params }) => { try { const id = params.id; if (!id) return apiError('CONVERSATION_NOT_FOUND', 'Conversation not found.', 404); const deleted = await getDb().delete(schema.conversations).where(eq(schema.conversations.id, id)).returning({ id: schema.conversations.id }); if (!deleted.length) return apiError('CONVERSATION_NOT_FOUND', 'Conversation not found.', 404); return new Response(null, { status: 204 }); } catch (error) { return handleApiError(error); } };
